#!/usr/bin/env bash

#
# Reset the global variables used for autocomplete and fill hints.
#
# @return void
shellNS_completion_reset() {
  COMPREPLY=()
  SHELLNS_CURRENTPROMPT_IN_NAMESPACE="1"
  SHELLNS_CURRENTPROMPT_NAMESPACE=""
  SHELLNS_CURRENTPROMPT_NAMESPACE_COMPLETIONS_LIST=""

  SHELLNS_CURRENTPROMPT_FUNCTION_MAINNS=
  SHELLNS_CURRENTPROMPT_FUNCTION_NAME=""
  SHELLNS_CURRENTPROMPT_FUNCTION_ARGUMENTS=()
}